var mocks={
    ApiProxy:{
        apiCall:function(){},
        newGame:function(){},
        newTurn:function(){}
    },
    PlayerSwitcher:{
        playerOne:'',
        playerTwo:'',
        gameBoard:'',
        currentPlayer:0,
        playerSwitch:function(){},
        playerSwap:function(){}
    },
    WinDecider:{
        winner:1,
        theWinner:function(){}
    },
    $state:{
        current:'lobby',
        go:function(){}
    }
};